defmodule SelectoNorthwind.Seeds.NorthwindData do
  @moduledoc """
  Contains all the static Northwind data used by the seeder.
  Separated from the main seeder module for better organization.
  """

  def categories_data do
    [
      %{id: 1, category_name: "Beverages", description: "Soft drinks, coffees, teas, beers, and ales"},
      %{id: 2, category_name: "Condiments", description: "Sweet and savory sauces, relishes, spreads, and seasonings"},
      %{id: 3, category_name: "Confections", description: "Desserts, candies, and sweet breads"},
      %{id: 4, category_name: "Dairy Products", description: "Cheeses"},
      %{id: 5, category_name: "Grains/Cereals", description: "Breads, crackers, pasta, and cereal"},
      %{id: 6, category_name: "Meat/Poultry", description: "Prepared meats"},
      %{id: 7, category_name: "Produce", description: "Dried fruit and bean curd"},
      %{id: 8, category_name: "Seafood", description: "Seaweed and fish"}
    ]
  end

  def customers_data do
    [
      %{customer_id: "ALFKI", company_name: "Alfreds Futterkiste", contact_name: "Maria Anders", contact_title: "Sales Representative", address: "Obere Str. 57", city: "Berlin", postal_code: "12209", country: "Germany", phone: "030-0074321", fax: "030-0076545"},
      %{customer_id: "ANATR", company_name: "Ana Trujillo Emparedados y helados", contact_name: "Ana Trujillo", contact_title: "Owner", address: "Avda. de la Constitución 2222", city: "México D.F.", postal_code: "05021", country: "Mexico", phone: "(5) 555-4729", fax: "(5) 555-3745"},
      %{customer_id: "ANTON", company_name: "Antonio Moreno Taquería", contact_name: "Antonio Moreno", contact_title: "Owner", address: "Mataderos  2312", city: "México D.F.", postal_code: "05023", country: "Mexico", phone: "(5) 555-3932"},
      %{customer_id: "AROUT", company_name: "Around the Horn", contact_name: "Thomas Hardy", contact_title: "Sales Representative", address: "120 Hanover Sq.", city: "London", postal_code: "WA1 1DP", country: "UK", phone: "(171) 555-7788", fax: "(171) 555-6750"},
      %{customer_id: "BERGS", company_name: "Berglunds snabbköp", contact_name: "Christina Berglund", contact_title: "Order Administrator", address: "Berguvsvägen  8", city: "Luleå", postal_code: "S-958 22", country: "Sweden", phone: "0921-12 34 65", fax: "0921-12 34 67"},
      %{customer_id: "BLAUS", company_name: "Blauer See Delikatessen", contact_name: "Hanna Moos", contact_title: "Sales Representative", address: "Forsterstr. 57", city: "Mannheim", postal_code: "68306", country: "Germany", phone: "0621-08460", fax: "0621-08924"},
      %{customer_id: "BLONP", company_name: "Blondesddsl père et fils", contact_name: "Frédérique Citeaux", contact_title: "Marketing Manager", address: "24, place Kléber", city: "Strasbourg", postal_code: "67000", country: "France", phone: "88.60.15.31", fax: "88.60.15.32"},
      %{customer_id: "BOLID", company_name: "Bólido Comidas preparadas", contact_name: "Martín Sommer", contact_title: "Owner", address: "C/ Araquil, 67", city: "Madrid", postal_code: "28023", country: "Spain", phone: "(91) 555 22 82", fax: "(91) 555 91 99"},
      %{customer_id: "BONAP", company_name: "Bon app'", contact_name: "Laurence Lebihan", contact_title: "Owner", address: "12, rue des Bouchers", city: "Marseille", postal_code: "13008", country: "France", phone: "91.24.45.40", fax: "91.24.45.41"},
      %{customer_id: "BOTTM", company_name: "Bottom-Dollar Markets", contact_name: "Elizabeth Lincoln", contact_title: "Accounting Manager", address: "23 Tsawassen Blvd.", city: "Tsawassen", region: "BC", postal_code: "T2F 8M4", country: "Canada", phone: "(604) 555-4729", fax: "(604) 555-3745"},
      %{customer_id: "BSBEV", company_name: "B's Beverages", contact_name: "Victoria Ashworth", contact_title: "Sales Representative", address: "Fauntleroy Circus", city: "London", postal_code: "EC2 5NT", country: "UK", phone: "(171) 555-1212"},
      %{customer_id: "CACTU", company_name: "Cactus Comidas para llevar", contact_name: "Patricio Simpson", contact_title: "Sales Agent", address: "Cerrito 333", city: "Buenos Aires", postal_code: "1010", country: "Argentina", phone: "(1) 135-5555", fax: "(1) 135-4892"},
      %{customer_id: "CENTC", company_name: "Centro comercial Moctezuma", contact_name: "Francisco Chang", contact_title: "Marketing Manager", address: "Sierras de Granada 9993", city: "México D.F.", postal_code: "05022", country: "Mexico", phone: "(5) 555-3392", fax: "(5) 555-7293"},
      %{customer_id: "CHOPS", company_name: "Chop-suey Chinese", contact_name: "Yang Wang", contact_title: "Owner", address: "Hauptstr. 29", city: "Bern", postal_code: "3012", country: "Switzerland", phone: "0452-076545"},
      %{customer_id: "COMMI", company_name: "Comércio Mineiro", contact_name: "Pedro Afonso", contact_title: "Sales Associate", address: "Av. dos Lusíadas, 23", city: "Sao Paulo", region: "SP", postal_code: "05432-043", country: "Brazil", phone: "(11) 555-7647"},
      %{customer_id: "CONSH", company_name: "Consolidated Holdings", contact_name: "Elizabeth Brown", contact_title: "Sales Representative", address: "Berkeley Gardens 12  Brewery", city: "London", postal_code: "WX1 6LT", country: "UK", phone: "(171) 555-2282", fax: "(171) 555-9199"},
      %{customer_id: "DRACD", company_name: "Drachenblut Delikatessen", contact_name: "Sven Ottlieb", contact_title: "Order Administrator", address: "Walserweg 21", city: "Aachen", postal_code: "52066", country: "Germany", phone: "0241-039123", fax: "0241-059428"},
      %{customer_id: "DUMON", company_name: "Du monde entier", contact_name: "Janine Labrune", contact_title: "Owner", address: "67, rue des Cinquante Otages", city: "Nantes", postal_code: "44000", country: "France", phone: "40.67.88.88", fax: "40.67.89.89"},
      %{customer_id: "EASTC", company_name: "Eastern Connection", contact_name: "Ann Devon", contact_title: "Sales Agent", address: "35 King George", city: "London", postal_code: "WX3 6FW", country: "UK", phone: "(171) 555-0297", fax: "(171) 555-3373"},
      %{customer_id: "ERNSH", company_name: "Ernst Handel", contact_name: "Roland Mendel", contact_title: "Sales Manager", address: "Kirchgasse 6", city: "Graz", postal_code: "8010", country: "Austria", phone: "7675-3425", fax: "7675-3426"},
      %{customer_id: "FAMIA", company_name: "Familia Arquibaldo", contact_name: "Aria Cruz", contact_title: "Marketing Assistant", address: "Rua Orós, 92", city: "Sao Paulo", region: "SP", postal_code: "05442-030", country: "Brazil", phone: "(11) 555-9857"},
      %{customer_id: "FISSA", company_name: "FISSA Fabrica Inter. Salchichas S.A.", contact_name: "Diego Roel", contact_title: "Accounting Manager", address: "C/ Moralzarzal, 86", city: "Madrid", postal_code: "28034", country: "Spain", phone: "(91) 555 94 44", fax: "(91) 555 55 93"},
      %{customer_id: "FOLIG", company_name: "Folies gourmandes", contact_name: "Martine Rancé", contact_title: "Assistant Sales Agent", address: "184, chaussée de Tournai", city: "Lille", postal_code: "59000", country: "France", phone: "20.16.10.16", fax: "20.16.10.17"},
      %{customer_id: "FOLKO", company_name: "Folk och fä HB", contact_name: "Maria Larsson", contact_title: "Owner", address: "Åkergatan 24", city: "Bräcke", postal_code: "S-844 67", country: "Sweden", phone: "0695-34 67 21"},
      %{customer_id: "FRANK", company_name: "Frankenversand", contact_name: "Peter Franken", contact_title: "Marketing Manager", address: "Berliner Platz 43", city: "München", postal_code: "80805", country: "Germany", phone: "089-0877310", fax: "089-0877451"},
      %{customer_id: "FRANR", company_name: "France restauration", contact_name: "Carine Schmitt", contact_title: "Marketing Manager", address: "54, rue Royale", city: "Nantes", postal_code: "44000", country: "France", phone: "40.32.21.21", fax: "40.32.21.20"},
      %{customer_id: "FRANS", company_name: "Franchi S.p.A.", contact_name: "Paolo Accorti", contact_title: "Sales Representative", address: "Via Monte Bianco 34", city: "Torino", postal_code: "10100", country: "Italy", phone: "011-4988260", fax: "011-4988261"},
      %{customer_id: "FURIB", company_name: "Furia Bacalhau e Frutos do Mar", contact_name: "Lino Rodriguez", contact_title: "Sales Manager", address: "Jardim das rosas n. 32", city: "Lisboa", postal_code: "1675", country: "Portugal", phone: "(1) 354-2534", fax: "(1) 354-2535"},
      %{customer_id: "GALED", company_name: "Galería del gastrónomo", contact_name: "Eduardo Saavedra", contact_title: "Marketing Manager", address: "Rambla de Cataluña, 23", city: "Barcelona", postal_code: "08022", country: "Spain", phone: "(93) 203 4560", fax: "(93) 203 4561"},
      %{customer_id: "GODOS", company_name: "Godos Cocina Típica", contact_name: "José Pedro Freyre", contact_title: "Sales Manager", address: "C/ Romero, 33", city: "Sevilla", postal_code: "41101", country: "Spain", phone: "(95) 555 82 82"},
      %{customer_id: "GOURL", company_name: "Gourmet Lanchonetes", contact_name: "André Fonseca", contact_title: "Sales Associate", address: "Av. Brasil, 442", city: "Campinas", region: "SP", postal_code: "04876-786", country: "Brazil", phone: "(11) 555-9482"},
      %{customer_id: "GREAL", company_name: "Great Lakes Food Market", contact_name: "Howard Snyder", contact_title: "Marketing Manager", address: "2732 Baker Blvd.", city: "Eugene", region: "OR", postal_code: "97403", country: "USA", phone: "(503) 555-7555"},
      %{customer_id: "GROSR", company_name: "GROSELLA-Restaurante", contact_name: "Manuel Pereira", contact_title: "Owner", address: "5ª Ave. Los Palos Grandes", city: "Caracas", region: "DF", postal_code: "1081", country: "Venezuela", phone: "(2) 283-2951", fax: "(2) 283-3397"},
      %{customer_id: "HANAR", company_name: "Hanari Carnes", contact_name: "Mario Pontes", contact_title: "Accounting Manager", address: "Rua do Paço, 67", city: "Rio de Janeiro", region: "RJ", postal_code: "05454-876", country: "Brazil", phone: "(21) 555-0091", fax: "(21) 555-8765"},
      %{customer_id: "HILAA", company_name: "HILARION-Abastos", contact_name: "Carlos Hernández", contact_title: "Sales Representative", address: "Carrera 22 con Ave. Carlos Soublette #8-35", city: "San Cristóbal", region: "Táchira", postal_code: "5022", country: "Venezuela", phone: "(5) 555-1340", fax: "(5) 555-1948"},
      %{customer_id: "HUNGC", company_name: "Hungry Coyote Import Store", contact_name: "Yoshi Latimer", contact_title: "Sales Representative", address: "City Center Plaza 516 Main St.", city: "Elgin", region: "OR", postal_code: "97827", country: "USA", phone: "(503) 555-6874", fax: "(503) 555-2376"},
      %{customer_id: "HUNGO", company_name: "Hungry Owl All-Night Grocers", contact_name: "Patricia McKenna", contact_title: "Sales Associate", address: "8 Johnstown Road", city: "Cork", region: "Co. Cork", country: "Ireland", phone: "2967 542", fax: "2967 3333"},
      %{customer_id: "ISLAT", company_name: "Island Trading", contact_name: "Helen Bennett", contact_title: "Marketing Manager", address: "Garden House Crowther Way", city: "Cowes", region: "Isle of Wight", postal_code: "PO31 7PJ", country: "UK", phone: "(198) 555-8888"},
      %{customer_id: "KOENE", company_name: "Königlich Essen", contact_name: "Philip Cramer", contact_title: "Sales Associate", address: "Maubelstr. 90", city: "Brandenburg", postal_code: "14776", country: "Germany", phone: "0555-09876"},
      %{customer_id: "LACOR", company_name: "La corne d'abondance", contact_name: "Daniel Tonini", contact_title: "Sales Representative", address: "67, avenue de l'Europe", city: "Versailles", postal_code: "78000", country: "France", phone: "30.59.84.10", fax: "30.59.85.11"},
      %{customer_id: "LAMAI", company_name: "La maison d'Asie", contact_name: "Annette Roulet", contact_title: "Sales Manager", address: "1 rue Alsace-Lorraine", city: "Toulouse", postal_code: "31000", country: "France", phone: "61.77.61.10", fax: "61.77.61.11"},
      %{customer_id: "LAUGB", company_name: "Laughing Bacchus Wine Cellars", contact_name: "Yoshi Tannamuri", contact_title: "Marketing Assistant", address: "1900 Oak St.", city: "Vancouver", region: "BC", postal_code: "V3F 2K1", country: "Canada", phone: "(604) 555-3392", fax: "(604) 555-7293"},
      %{customer_id: "LAZYK", company_name: "Lazy K Kountry Store", contact_name: "John Steel", contact_title: "Marketing Manager", address: "12 Orchestra Terrace", city: "Walla Walla", region: "WA", postal_code: "99362", country: "USA", phone: "(509) 555-7969", fax: "(509) 555-6221"},
      %{customer_id: "LEHMS", company_name: "Lehmanns Marktstand", contact_name: "Renate Messner", contact_title: "Sales Representative", address: "Magazinweg 7", city: "Frankfurt a.M.", postal_code: "60528", country: "Germany", phone: "069-0245984", fax: "069-0245874"},
      %{customer_id: "LETSS", company_name: "Let's Stop N Shop", contact_name: "Jaime Yorres", contact_title: "Owner", address: "87 Polk St. Suite 5", city: "San Francisco", region: "CA", postal_code: "94117", country: "USA", phone: "(415) 555-5938"},
      %{customer_id: "LILAS", company_name: "LILA-Supermercado", contact_name: "Carlos González", contact_title: "Accounting Manager", address: "Carrera 52 con Ave. Bolívar #65-98 Llano Largo", city: "Barquisimeto", region: "Lara", postal_code: "3508", country: "Venezuela", phone: "(9) 331-6954", fax: "(9) 331-7256"},
      %{customer_id: "LINOD", company_name: "LINO-Delicateses", contact_name: "Felipe Izquierdo", contact_title: "Owner", address: "Ave. 5 de Mayo Porlamar", city: "I. de Margarita", region: "Nueva Esparta", postal_code: "4980", country: "Venezuela", phone: "(8) 34-56-12", fax: "(8) 34-93-93"},
      %{customer_id: "LONEP", company_name: "Lonesome Pine Restaurant", contact_name: "Fran Wilson", contact_title: "Sales Manager", address: "89 Chiaroscuro Rd.", city: "Portland", region: "OR", postal_code: "97219", country: "USA", phone: "(503) 555-9573", fax: "(503) 555-9646"},
      %{customer_id: "MAGAA", company_name: "Magazzini Alimentari Riuniti", contact_name: "Giovanni Rovelli", contact_title: "Marketing Manager", address: "Via Ludovico il Moro 22", city: "Bergamo", postal_code: "24100", country: "Italy", phone: "035-640230", fax: "035-640231"},
      %{customer_id: "MAISD", company_name: "Maison Dewey", contact_name: "Catherine Dewey", contact_title: "Sales Agent", address: "Rue Joseph-Bens 532", city: "Bruxelles", postal_code: "B-1180", country: "Belgium", phone: "(02) 201 24 67", fax: "(02) 201 24 68"},
      %{customer_id: "MEREP", company_name: "Mère Paillarde", contact_name: "Jean Fresnière", contact_title: "Marketing Assistant", address: "43 rue St. Laurent", city: "Montréal", region: "Québec", postal_code: "H1J 1C3", country: "Canada", phone: "(514) 555-8054", fax: "(514) 555-8055"},
      %{customer_id: "MORGK", company_name: "Morgenstern Gesundkost", contact_name: "Alexander Feuer", contact_title: "Marketing Assistant", address: "Heerstr. 22", city: "Leipzig", postal_code: "04179", country: "Germany", phone: "0342-023176"},
      %{customer_id: "NORTS", company_name: "North/South", contact_name: "Simon Crowther", contact_title: "Sales Associate", address: "South House 300 Queensbridge", city: "London", postal_code: "SW7 1RZ", country: "UK", phone: "(171) 555-7733", fax: "(171) 555-2530"},
      %{customer_id: "OCEAN", company_name: "Océano Atlántico Ltda.", contact_name: "Yvonne Moncada", contact_title: "Sales Agent", address: "Ing. Gustavo Moncada 8585 Piso 20-A", city: "Buenos Aires", postal_code: "1010", country: "Argentina", phone: "(1) 135-5333", fax: "(1) 135-5535"},
      %{customer_id: "OLDWO", company_name: "Old World Delicatessen", contact_name: "Rene Phillips", contact_title: "Sales Representative", address: "2743 Bering St.", city: "Anchorage", region: "AK", postal_code: "99508", country: "USA", phone: "(907) 555-7584", fax: "(907) 555-2880"},
      %{customer_id: "OTTIK", company_name: "Ottilies Käseladen", contact_name: "Henriette Pfalzheim", contact_title: "Owner", address: "Mehrheimerstr. 369", city: "Köln", postal_code: "50739", country: "Germany", phone: "0221-0644327", fax: "0221-0765721"},
      %{customer_id: "PARIS", company_name: "Paris spécialités", contact_name: "Marie Bertrand", contact_title: "Owner", address: "265, boulevard Charonne", city: "Paris", postal_code: "75012", country: "France", phone: "(1) 42.34.22.66", fax: "(1) 42.34.22.77"},
      %{customer_id: "PERIC", company_name: "Pericles Comidas clásicas", contact_name: "Guillermo Fernández", contact_title: "Sales Representative", address: "Calle Dr. Jorge Cash 321", city: "México D.F.", postal_code: "05033", country: "Mexico", phone: "(5) 552-3745", fax: "(5) 545-3745"},
      %{customer_id: "PICCO", company_name: "Piccolo und mehr", contact_name: "Georg Pipps", contact_title: "Sales Manager", address: "Geislweg 14", city: "Salzburg", postal_code: "5020", country: "Austria", phone: "6562-9722", fax: "6562-9723"},
      %{customer_id: "PRINI", company_name: "Princesa Isabel Vinhos", contact_name: "Isabel de Castro", contact_title: "Sales Representative", address: "Estrada da saúde n. 58", city: "Lisboa", postal_code: "1756", country: "Portugal", phone: "(1) 356-5634"},
      %{customer_id: "QUEDE", company_name: "Que Delícia", contact_name: "Bernardo Batista", contact_title: "Accounting Manager", address: "Rua da Panificadora, 12", city: "Rio de Janeiro", region: "RJ", postal_code: "02389-673", country: "Brazil", phone: "(21) 555-4252", fax: "(21) 555-4545"},
      %{customer_id: "QUEEN", company_name: "Queen Cozinha", contact_name: "Lúcia Carvalho", contact_title: "Marketing Assistant", address: "Alameda dos Canàrios, 891", city: "Sao Paulo", region: "SP", postal_code: "05487-020", country: "Brazil", phone: "(11) 555-1189"},
      %{customer_id: "QUICK", company_name: "QUICK-Stop", contact_name: "Horst Kloss", contact_title: "Accounting Manager", address: "Taucherstraße 10", city: "Cunewalde", postal_code: "01307", country: "Germany", phone: "0372-035188"},
      %{customer_id: "RANCH", company_name: "Rancho grande", contact_name: "Sergio Gutiérrez", contact_title: "Sales Representative", address: "Av. del Libertador 900", city: "Buenos Aires", postal_code: "1010", country: "Argentina", phone: "(1) 123-5555", fax: "(1) 123-5556"},
      %{customer_id: "RATTC", company_name: "Rattlesnake Canyon Grocery", contact_name: "Paula Wilson", contact_title: "Assistant Sales Representative", address: "2817 Milton Dr.", city: "Albuquerque", region: "NM", postal_code: "87110", country: "USA", phone: "(505) 555-5939", fax: "(505) 555-3620"},
      %{customer_id: "REGGC", company_name: "Reggiani Caseifici", contact_name: "Maurizio Moroni", contact_title: "Sales Associate", address: "Strada Provinciale 124", city: "Reggio Emilia", postal_code: "42100", country: "Italy", phone: "0522-556721", fax: "0522-556722"},
      %{customer_id: "RICAR", company_name: "Ricardo Adocicados", contact_name: "Janete Limeira", contact_title: "Assistant Sales Agent", address: "Av. Copacabana, 267", city: "Rio de Janeiro", region: "RJ", postal_code: "02389-890", country: "Brazil", phone: "(21) 555-3412"},
      %{customer_id: "RICSU", company_name: "Richter Supermarkt", contact_name: "Michael Holz", contact_title: "Sales Manager", address: "Grenzacherweg 237", city: "Genève", postal_code: "1203", country: "Switzerland", phone: "0897-034214"},
      %{customer_id: "ROMEY", company_name: "Romero y tomillo", contact_name: "Alejandra Camino", contact_title: "Accounting Manager", address: "Gran Vía, 1", city: "Madrid", postal_code: "28001", country: "Spain", phone: "(91) 745 6200", fax: "(91) 745 6210"},
      %{customer_id: "SANTG", company_name: "Santé Gourmet", contact_name: "Jonas Bergulfsen", contact_title: "Owner", address: "Erling Skakkes gate 78", city: "Stavern", postal_code: "4110", country: "Norway", phone: "07-98 92 35", fax: "07-98 92 47"},
      %{customer_id: "SAVEA", company_name: "Save-a-lot Markets", contact_name: "Jose Pavarotti", contact_title: "Sales Representative", address: "187 Suffolk Ln.", city: "Boise", region: "ID", postal_code: "83720", country: "USA", phone: "(208) 555-8097"},
      %{customer_id: "SEVES", company_name: "Seven Seas Imports", contact_name: "Hari Kumar", contact_title: "Sales Manager", address: "90 Wadhurst Rd.", city: "London", postal_code: "OX15 4NB", country: "UK", phone: "(171) 555-1717", fax: "(171) 555-5646"},
      %{customer_id: "SIMOB", company_name: "Simons bistro", contact_name: "Jytte Petersen", contact_title: "Owner", address: "Vinbæltet 34", city: "Kobenhavn", postal_code: "1734", country: "Denmark", phone: "31 12 34 56", fax: "31 13 35 57"},
      %{customer_id: "SPECD", company_name: "Spécialités du monde", contact_name: "Dominique Perrier", contact_title: "Marketing Manager", address: "25, rue Lauriston", city: "Paris", postal_code: "75016", country: "France", phone: "(1) 47.55.60.10", fax: "(1) 47.55.60.20"},
      %{customer_id: "SPLIR", company_name: "Split Rail Beer & Ale", contact_name: "Art Braunschweiger", contact_title: "Sales Manager", address: "P.O. Box 555", city: "Lander", region: "WY", postal_code: "82520", country: "USA", phone: "(307) 555-4680", fax: "(307) 555-6525"},
      %{customer_id: "SUPRD", company_name: "Suprêmes délices", contact_name: "Pascale Cartrain", contact_title: "Accounting Manager", address: "Boulevard Tirou, 255", city: "Charleroi", postal_code: "B-6000", country: "Belgium", phone: "(071) 23 67 22 20", fax: "(071) 23 67 22 21"},
      %{customer_id: "THEBI", company_name: "The Big Cheese", contact_name: "Liz Nixon", contact_title: "Marketing Manager", address: "89 Jefferson Way Suite 2", city: "Portland", region: "OR", postal_code: "97201", country: "USA", phone: "(503) 555-3612"},
      %{customer_id: "THECR", company_name: "The Cracker Box", contact_name: "Liu Wong", contact_title: "Marketing Assistant", address: "55 Grizzly Peak Rd.", city: "Butte", region: "MT", postal_code: "59801", country: "USA", phone: "(406) 555-5834", fax: "(406) 555-8083"},
      %{customer_id: "TOMSP", company_name: "Toms Spezialitäten", contact_name: "Karin Josephs", contact_title: "Marketing Manager", address: "Luisenstr. 48", city: "Münster", postal_code: "44087", country: "Germany", phone: "0251-031259", fax: "0251-035695"},
      %{customer_id: "TORTU", company_name: "Tortuga Restaurante", contact_name: "Miguel Angel Paolino", contact_title: "Owner", address: "Avda. Azteca 123", city: "México D.F.", postal_code: "05033", country: "Mexico", phone: "(5) 555-2933"},
      %{customer_id: "TRADH", company_name: "Tradição Hipermercados", contact_name: "Anabela Domingues", contact_title: "Sales Representative", address: "Av. Inês de Castro, 414", city: "Sao Paulo", region: "SP", postal_code: "05634-030", country: "Brazil", phone: "(11) 555-2167", fax: "(11) 555-2168"},
      %{customer_id: "TRAIH", company_name: "Trail's Head Gourmet Provisioners", contact_name: "Helvetius Nagy", contact_title: "Sales Associate", address: "722 DaVinci Blvd.", city: "Kirkland", region: "WA", postal_code: "98034", country: "USA", phone: "(206) 555-8257", fax: "(206) 555-2174"},
      %{customer_id: "VAFFE", company_name: "Vaffeljernet", contact_name: "Palle Ibsen", contact_title: "Sales Manager", address: "Smagsloget 45", city: "Århus", postal_code: "8200", country: "Denmark", phone: "86 21 32 43", fax: "86 22 33 44"},
      %{customer_id: "VICTE", company_name: "Victuailles en stock", contact_name: "Mary Saveley", contact_title: "Sales Agent", address: "2, rue du Commerce", city: "Lyon", postal_code: "69004", country: "France", phone: "78.32.54.86", fax: "78.32.54.87"},
      %{customer_id: "VINET", company_name: "Vins et alcools Chevalier", contact_name: "Paul Henriot", contact_title: "Accounting Manager", address: "59 rue de l'Abbaye", city: "Reims", postal_code: "51100", country: "France", phone: "26.47.15.10", fax: "26.47.15.11"},
      %{customer_id: "WANDK", company_name: "Die Wandernde Kuh", contact_name: "Rita Müller", contact_title: "Sales Representative", address: "Adenauerallee 900", city: "Stuttgart", postal_code: "70563", country: "Germany", phone: "0711-020361", fax: "0711-035428"},
      %{customer_id: "WARTH", company_name: "Wartian Herkku", contact_name: "Pirkko Koskitalo", contact_title: "Accounting Manager", address: "Torikatu 38", city: "Oulu", postal_code: "90110", country: "Finland", phone: "981-443655", fax: "981-443655"},
      %{customer_id: "WELLI", company_name: "Wellington Importadora", contact_name: "Paula Parente", contact_title: "Sales Manager", address: "Rua do Mercado, 12", city: "Resende", region: "SP", postal_code: "08737-363", country: "Brazil", phone: "(14) 555-8122"},
      %{customer_id: "WHITC", company_name: "White Clover Markets", contact_name: "Karl Jablonski", contact_title: "Owner", address: "305 - 14th Ave. S. Suite 3B", city: "Seattle", region: "WA", postal_code: "98128", country: "USA", phone: "(206) 555-4112", fax: "(206) 555-4115"},
      %{customer_id: "WILMK", company_name: "Wilman Kala", contact_name: "Matti Karttunen", contact_title: "Owner/Marketing Assistant", address: "Keskuskatu 45", city: "Helsinki", postal_code: "21240", country: "Finland", phone: "90-224 8858", fax: "90-224 8858"},
      %{customer_id: "WOLZA", company_name: "Wolski  Zajazd", contact_name: "Zbyszek Piestrzeniewicz", contact_title: "Owner", address: "ul. Filtrowa 68", city: "Warszawa", postal_code: "01-012", country: "Poland", phone: "(26) 642-7012", fax: "(26) 642-7012"}
    ]
  end

  # TODO: For brevity, only showing sample data.
  # Copy the complete data arrays from priv/repo/complete_seeds.exs

  def employees_data do
    [
      %{id: 2, last_name: "Fuller", first_name: "Andrew", title: "Vice President, Sales", title_of_courtesy: "Dr.", birth_date: ~D[1952-02-19], hire_date: ~D[1992-08-14], address: "908 W. Capital Way", city: "Tacoma", region: "WA", postal_code: "98401", country: "USA", home_phone: "(206) 555-9482", extension: "3457", notes: "Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.", reports_to: nil},
      %{id: 1, last_name: "Davolio", first_name: "Nancy", title: "Sales Representative", title_of_courtesy: "Ms.", birth_date: ~D[1948-12-08], hire_date: ~D[1992-05-01], address: "507 - 20th Ave. E.\nApt. 2A", city: "Seattle", region: "WA", postal_code: "98122", country: "USA", home_phone: "(206) 555-9857", extension: "5467", notes: "Education includes a BA in psychology from Colorado State University in 1970.  She also completed The Art of the Cold Call.  Nancy is a member of Toastmasters International.", reports_to: 2},
      %{id: 3, last_name: "Leverling", first_name: "Janet", title: "Sales Representative", title_of_courtesy: "Ms.", birth_date: ~D[1963-08-30], hire_date: ~D[1992-04-01], address: "722 Moss Bay Blvd.", city: "Kirkland", region: "WA", postal_code: "98033", country: "USA", home_phone: "(206) 555-3412", extension: "3355", notes: "Janet has a BS degree in chemistry from Boston College (1984).  She has also completed a certificate program in food retailing management.  Janet was hired as a sales associate in 1991 and promoted to sales representative in February 1992.", reports_to: 2},
      %{id: 4, last_name: "Peacock", first_name: "Margaret", title: "Sales Representative", title_of_courtesy: "Mrs.", birth_date: ~D[1937-09-19], hire_date: ~D[1993-05-03], address: "4110 Old Redmond Rd.", city: "Redmond", region: "WA", postal_code: "98052", country: "USA", home_phone: "(206) 555-8122", extension: "5176", notes: "Margaret holds a BA in English literature from Concordia College (1958) and an MA from the American Institute of Culinary Arts (1966).  She was assigned to the London office temporarily from July through November 1992.", reports_to: 2},
      %{id: 5, last_name: "Buchanan", first_name: "Steven", title: "Sales Manager", title_of_courtesy: "Mr.", birth_date: ~D[1955-03-04], hire_date: ~D[1993-10-17], address: "14 Garrett Hill", city: "London", postal_code: "SW1 8JR", country: "UK", home_phone: "(71) 555-4848", extension: "3453", notes: "Steven Buchanan graduated from St. Andrews University, Scotland, with a BSC degree in 1976.  Upon joining the company as a sales representative in 1992, he spent 6 months in an orientation program at the Seattle office and then returned to his permanent post in London.  He was promoted to sales manager in March 1993.  Mr. Buchanan has completed the courses 'Successful Telemarketing' and 'International Sales Management.'  He is fluent in French.", reports_to: 2},
      %{id: 8, last_name: "Callahan", first_name: "Laura", title: "Inside Sales Coordinator", title_of_courtesy: "Ms.", birth_date: ~D[1958-01-09], hire_date: ~D[1994-03-05], address: "4726 - 11th Ave. N.E.", city: "Seattle", region: "WA", postal_code: "98105", country: "USA", home_phone: "(206) 555-1189", extension: "2344", notes: "Laura received a BA in psychology from the University of Washington.  She has also completed a course in business French.  She reads and writes French.", reports_to: 2},
      %{id: 6, last_name: "Suyama", first_name: "Michael", title: "Sales Representative", title_of_courtesy: "Mr.", birth_date: ~D[1963-07-02], hire_date: ~D[1993-10-17], address: "Coventry House\nMiner Rd.", city: "London", postal_code: "EC2 7JR", country: "UK", home_phone: "(71) 555-7773", extension: "428", notes: "Michael is a graduate of Sussex University (MA, economics, 1983) and the University of California at Los Angeles (MBA, marketing, 1986).  He has also taken the courses 'Multi-Cultural Selling' and 'Time Management for the Sales Professional.'  He is fluent in Japanese and can read and write French, Portuguese, and Spanish.", reports_to: 5},
      %{id: 7, last_name: "King", first_name: "Robert", title: "Sales Representative", title_of_courtesy: "Mr.", birth_date: ~D[1960-05-29], hire_date: ~D[1994-01-02], address: "Edgeham Hollow\nWinchester Way", city: "London", postal_code: "RG1 9SP", country: "UK", home_phone: "(71) 555-5598", extension: "465", notes: "Robert King served in the Peace Corps and traveled extensively before completing his degree in English at the University of Michigan in 1992, the year he joined the company.  After completing a course entitled 'Selling in Europe,' he was transferred to the London office in March 1993.", reports_to: 5},
      %{id: 9, last_name: "Dodsworth", first_name: "Anne", title: "Sales Representative", title_of_courtesy: "Ms.", birth_date: ~D[1966-01-27], hire_date: ~D[1994-11-15], address: "7 Houndstooth Rd.", city: "London", postal_code: "WG2 7LT", country: "UK", home_phone: "(71) 555-4444", extension: "452", notes: "Anne has a BA degree in English from St. Lawrence College.  She is fluent in French and German.", reports_to: 5}
    ]
  end

  def suppliers_data do
    [
      %{id: 1, company_name: "Exotic Liquids", contact_name: "Charlotte Cooper", contact_title: "Purchasing Manager", address: "49 Gilbert St.", city: "London", postal_code: "EC1 4SD", country: "UK", phone: "(171) 555-2222"},
      %{id: 2, company_name: "New Orleans Cajun Delights", contact_name: "Shelley Burke", contact_title: "Order Administrator", address: "P.O. Box 78934", city: "New Orleans", region: "LA", postal_code: "70117", country: "USA", phone: "(100) 555-4822"},
      %{id: 3, company_name: "Grandma Kelly's Homestead", contact_name: "Regina Murphy", contact_title: "Sales Representative", address: "707 Oxford Rd.", city: "Ann Arbor", region: "MI", postal_code: "48104", country: "USA", phone: "(313) 555-5735", fax: "(313) 555-3349"},
      %{id: 4, company_name: "Tokyo Traders", contact_name: "Yoshi Nagase", contact_title: "Marketing Manager", address: "9-8 Sekimai Musashino-shi", city: "Tokyo", postal_code: "100", country: "Japan", phone: "(03) 3555-5011"},
      %{id: 5, company_name: "Cooperativa de Quesos 'Las Cabras'", contact_name: "Antonio del Valle Saavedra", contact_title: "Export Administrator", address: "Calle del Rosal 4", city: "Oviedo", region: "Asturias", postal_code: "33007", country: "Spain", phone: "(98) 598 76 98"},
      %{id: 6, company_name: "Mayumi's", contact_name: "Mayumi Ohno", contact_title: "Marketing Representative", address: "92 Setsuko Chuo-ku", city: "Osaka", postal_code: "545", country: "Japan", phone: "(06) 431-7877", fax: "(06) 431-7877"},
      %{id: 7, company_name: "Pavlova, Ltd.", contact_name: "Ian Devling", contact_title: "Marketing Manager", address: "74 Rose St. Moonie Ponds", city: "Melbourne", region: "Victoria", postal_code: "3058", country: "Australia", phone: "(03) 444-2343", fax: "(03) 444-6588"},
      %{id: 8, company_name: "Specialty Biscuits, Ltd.", contact_name: "Peter Wilson", contact_title: "Sales Representative", address: "29 King's Way", city: "Manchester", postal_code: "M14 GSD", country: "UK", phone: "(161) 555-4448"},
      %{id: 9, company_name: "PB Knäckebröd AB", contact_name: "Lars Peterson", contact_title: "Sales Agent", address: "Kaloadagatan 13", city: "Göteborg", postal_code: "S-345 67", country: "Sweden", phone: "031-987 65 43", fax: "031-987 65 91"},
      %{id: 10, company_name: "Refrescos Americanas LTDA", contact_name: "Carlos Diaz", contact_title: "Marketing Manager", address: "Av. das Americanas 12.890", city: "São Paulo", postal_code: "5442", country: "Brazil", phone: "(11) 555 4640"},
      %{id: 11, company_name: "Heli Süßwaren GmbH & Co. KG", contact_name: "Petra Winkler", contact_title: "Sales Manager", address: "Tiergartenstraße 5", city: "Berlin", postal_code: "10785", country: "Germany", phone: "(010) 9984510"},
      %{id: 12, company_name: "Plutzer Lebensmittelgroßmärkte AG", contact_name: "Martin Bein", contact_title: "International Marketing Mgr.", address: "Bogenallee 51", city: "Frankfurt", postal_code: "60439", country: "Germany", phone: "(069) 992755"},
      %{id: 13, company_name: "Nord-Ost-Fisch Handelsgesellschaft mbH", contact_name: "Sven Petersen", contact_title: "Coordinator Foreign Markets", address: "Frahmredder 112a", city: "Cuxhaven", postal_code: "27478", country: "Germany", phone: "(04721) 8713", fax: "(04721) 8714"},
      %{id: 14, company_name: "Formaggi Fortini s.r.l.", contact_name: "Elio Rossi", contact_title: "Sales Representative", address: "Viale Dante, 75", city: "Ravenna", postal_code: "48100", country: "Italy", phone: "(0544) 60323", fax: "(0544) 60603"},
      %{id: 15, company_name: "Norske Meierier", contact_name: "Beate Vileid", contact_title: "Marketing Manager", address: "Hatlevegen 5", city: "Sandvika", postal_code: "1320", country: "Norway", phone: "(0)2-953010"},
      %{id: 16, company_name: "Bigfoot Breweries", contact_name: "Cheryl Saylor", contact_title: "Regional Account Rep.", address: "3400 - 8th Avenue Suite 210", city: "Bend", region: "OR", postal_code: "97101", country: "USA", phone: "(503) 555-9931"},
      %{id: 17, company_name: "Svensk Sjöföda AB", contact_name: "Michael Björn", contact_title: "Sales Representative", address: "Brovallavägen 231", city: "Stockholm", postal_code: "S-123 45", country: "Sweden", phone: "08-123 45 67"},
      %{id: 18, company_name: "Aux joyeux ecclésiastiques", contact_name: "Guylène Nodier", contact_title: "Sales Manager", address: "203, Rue des Francs-Bourgeois", city: "Paris", postal_code: "75004", country: "France", phone: "(1) 03.83.00.68", fax: "(1) 03.83.00.62"},
      %{id: 19, company_name: "New England Seafood Cannery", contact_name: "Robb Merchant", contact_title: "Wholesale Account Agent", address: "Order Processing Dept. 2100 Paul Revere Blvd.", city: "Boston", region: "MA", postal_code: "02134", country: "USA", phone: "(617) 555-3267", fax: "(617) 555-3389"},
      %{id: 20, company_name: "Leka Trading", contact_name: "Chandra Leka", contact_title: "Owner", address: "471 Serangoon Loop, Suite #402", city: "Singapore", postal_code: "0512", country: "Singapore", phone: "555-8787"},
      %{id: 21, company_name: "Lyngbysild", contact_name: "Niels Petersen", contact_title: "Sales Manager", address: "Lyngbysild Fiskebakken 10", city: "Lyngby", postal_code: "2800", country: "Denmark", phone: "43844108", fax: "43844115"},
      %{id: 22, company_name: "Zaanse Snoepfabriek", contact_name: "Dirk Luchte", contact_title: "Accounting Manager", address: "Verkoop Rijnweg 22", city: "Zaandam", postal_code: "9999 ZZ", country: "Netherlands", phone: "(12345) 1212", fax: "(12345) 1210"},
      %{id: 23, company_name: "Karkki Oy", contact_name: "Anne Heikkonen", contact_title: "Product Manager", address: "Valtakatu 12", city: "Lappeenranta", postal_code: "53120", country: "Finland", phone: "(953) 10956"},
      %{id: 24, company_name: "G'day, Mate", contact_name: "Wendy Mackenzie", contact_title: "Sales Representative", address: "170 Prince Edward Parade Hunter's Hill", city: "Sydney", region: "NSW", postal_code: "2042", country: "Australia", phone: "(02) 555-5914", fax: "(02) 555-4873"},
      %{id: 25, company_name: "Ma Maison", contact_name: "Jean-Guy Lauzon", contact_title: "Marketing Manager", address: "2960 Rue St. Laurent", city: "Montréal", region: "Québec", postal_code: "H1J 1C3", country: "Canada", phone: "(514) 555-9022"},
      %{id: 26, company_name: "Pasta Buttini s.r.l.", contact_name: "Giovanni Giudici", contact_title: "Order Administrator", address: "Via dei Gelsomini, 153", city: "Salerno", postal_code: "84100", country: "Italy", phone: "(089) 6547665", fax: "(089) 6547667"},
      %{id: 27, company_name: "Escargots Nouveaux", contact_name: "Marie Delamare", contact_title: "Sales Manager", address: "22, rue H. Voiron", city: "Montceau", postal_code: "71300", country: "France", phone: "85.57.00.07"},
      %{id: 28, company_name: "Gai pâturage", contact_name: "Eliane Noz", contact_title: "Sales Representative", address: "Bat. B 3, rue des Alpes", city: "Annecy", postal_code: "74000", country: "France", phone: "38.76.98.06", fax: "38.76.98.58"},
      %{id: 29, company_name: "Forêts d'érables", contact_name: "Chantal Goulet", contact_title: "Accounting Manager", address: "148 rue Chasseur", city: "Ste-Hyacinthe", region: "Québec", postal_code: "J2S 7S8", country: "Canada", phone: "(514) 555-2955", fax: "(514) 555-2921"}
    ]
  end

  def products_data do
    [
      %{id: 1, product_name: "Chai", supplier_id: 1, category_id: 1, quantity_per_unit: "10 boxes x 20 bags", unit_price: Decimal.new("18.0000"), units_in_stock: 39, units_on_order: 0, reorder_level: 10, discontinued: false},
      %{id: 2, product_name: "Chang", supplier_id: 1, category_id: 1, quantity_per_unit: "24 - 12 oz bottles", unit_price: Decimal.new("19.0000"), units_in_stock: 17, units_on_order: 40, reorder_level: 25, discontinued: false},
      %{id: 3, product_name: "Aniseed Syrup", supplier_id: 1, category_id: 2, quantity_per_unit: "12 - 550 ml bottles", unit_price: Decimal.new("10.0000"), units_in_stock: 13, units_on_order: 70, reorder_level: 25, discontinued: false},
      %{id: 4, product_name: "Chef Anton's Cajun Seasoning", supplier_id: 2, category_id: 2, quantity_per_unit: "48 - 6 oz jars", unit_price: Decimal.new("22.0000"), units_in_stock: 53, units_on_order: 0, reorder_level: 0, discontinued: false},
      %{id: 5, product_name: "Chef Anton's Gumbo Mix", supplier_id: 2, category_id: 2, quantity_per_unit: "36 boxes", unit_price: Decimal.new("21.3500"), units_in_stock: 0, units_on_order: 0, reorder_level: 0, discontinued: true},
      %{id: 6, product_name: "Grandma's Boysenberry Spread", supplier_id: 3, category_id: 2, quantity_per_unit: "12 - 8 oz jars", unit_price: Decimal.new("25.0000"), units_in_stock: 120, units_on_order: 0, reorder_level: 25, discontinued: false},
      %{id: 7, product_name: "Uncle Bob's Organic Dried Pears", supplier_id: 3, category_id: 7, quantity_per_unit: "12 - 1 lb pkgs.", unit_price: Decimal.new("30.0000"), units_in_stock: 15, units_on_order: 0, reorder_level: 10, discontinued: false},
      %{id: 8, product_name: "Northwoods Cranberry Sauce", supplier_id: 3, category_id: 2, quantity_per_unit: "12 - 12 oz jars", unit_price: Decimal.new("40.0000"), units_in_stock: 6, units_on_order: 0, reorder_level: 0, discontinued: false},
      %{id: 9, product_name: "Mishi Kobe Niku", supplier_id: 4, category_id: 6, quantity_per_unit: "18 - 500 g pkgs.", unit_price: Decimal.new("97.0000"), units_in_stock: 29, units_on_order: 0, reorder_level: 0, discontinued: true},
      %{id: 10, product_name: "Ikura", supplier_id: 4, category_id: 8, quantity_per_unit: "12 - 200 ml jars", unit_price: Decimal.new("31.0000"), units_in_stock: 31, units_on_order: 0, reorder_level: 0, discontinued: false},
      %{id: 11, product_name: "Queso Cabrales", supplier_id: 5, category_id: 4, quantity_per_unit: "1 kg pkg.", unit_price: Decimal.new("21.0000"), units_in_stock: 22, units_on_order: 30, reorder_level: 30, discontinued: false},
      %{id: 12, product_name: "Queso Manchego La Pastora", supplier_id: 5, category_id: 4, quantity_per_unit: "10 - 500 g pkgs.", unit_price: Decimal.new("38.0000"), units_in_stock: 86, units_on_order: 0, reorder_level: 0, discontinued: false},
      %{id: 13, product_name: "Konbu", supplier_id: 6, category_id: 8, quantity_per_unit: "2 kg box", unit_price: Decimal.new("6.0000"), units_in_stock: 24, units_on_order: 0, reorder_level: 5, discontinued: false},
      %{id: 14, product_name: "Tofu", supplier_id: 6, category_id: 7, quantity_per_unit: "40 - 100 g pkgs.", unit_price: Decimal.new("23.2500"), units_in_stock: 35, units_on_order: 0, reorder_level: 0, discontinued: false},
      %{id: 15, product_name: "Genen Shouyu", supplier_id: 6, category_id: 2, quantity_per_unit: "24 - 250 ml bottles", unit_price: Decimal.new("15.5000"), units_in_stock: 39, units_on_order: 0, reorder_level: 5, discontinued: false},
      %{id: 16, product_name: "Pavlova", supplier_id: 7, category_id: 3, quantity_per_unit: "32 - 500 g boxes", unit_price: Decimal.new("17.4500"), units_in_stock: 29, units_on_order: 0, reorder_level: 10, discontinued: false},
      %{id: 17, product_name: "Alice Mutton", supplier_id: 7, category_id: 6, quantity_per_unit: "20 - 1 kg tins", unit_price: Decimal.new("39.0000"), units_in_stock: 0, units_on_order: 0, reorder_level: 0, discontinued: true},
      %{id: 18, product_name: "Carnarvon Tigers", supplier_id: 7, category_id: 8, quantity_per_unit: "16 kg pkg.", unit_price: Decimal.new("62.5000"), units_in_stock: 42, units_on_order: 0, reorder_level: 0, discontinued: false},
      %{id: 19, product_name: "Teatime Chocolate Biscuits", supplier_id: 8, category_id: 3, quantity_per_unit: "10 boxes x 12 pieces", unit_price: Decimal.new("9.2000"), units_in_stock: 25, units_on_order: 0, reorder_level: 5, discontinued: false},
      %{id: 20, product_name: "Sir Rodney's Marmalade", supplier_id: 8, category_id: 3, quantity_per_unit: "30 gift boxes", unit_price: Decimal.new("81.0000"), units_in_stock: 40, units_on_order: 0, reorder_level: 0, discontinued: false},
      %{id: 21, product_name: "Sir Rodney's Scones", supplier_id: 8, category_id: 3, quantity_per_unit: "24 pkgs. x 4 pieces", unit_price: Decimal.new("10.0000"), units_in_stock: 3, units_on_order: 40, reorder_level: 5, discontinued: false},
      %{id: 22, product_name: "Gustaf's Knäckebröd", supplier_id: 9, category_id: 5, quantity_per_unit: "24 - 500 g pkgs.", unit_price: Decimal.new("21.0000"), units_in_stock: 104, units_on_order: 0, reorder_level: 25, discontinued: false},
      %{id: 23, product_name: "Tunnbröd", supplier_id: 9, category_id: 5, quantity_per_unit: "12 - 250 g pkgs.", unit_price: Decimal.new("9.0000"), units_in_stock: 61, units_on_order: 0, reorder_level: 25, discontinued: false},
      %{id: 24, product_name: "Guaraná Fantástica", supplier_id: 10, category_id: 1, quantity_per_unit: "12 - 355 ml cans", unit_price: Decimal.new("4.5000"), units_in_stock: 20, units_on_order: 0, reorder_level: 0, discontinued: true},
      %{id: 25, product_name: "NuNuCa Nuß-Nougat-Creme", supplier_id: 11, category_id: 3, quantity_per_unit: "20 - 450 g glasses", unit_price: Decimal.new("14.0000"), units_in_stock: 76, units_on_order: 0, reorder_level: 30, discontinued: false},
      %{id: 26, product_name: "Gumbär Gummibärchen", supplier_id: 11, category_id: 3, quantity_per_unit: "100 - 250 g bags", unit_price: Decimal.new("31.2300"), units_in_stock: 15, units_on_order: 0, reorder_level: 0, discontinued: false},
      %{id: 27, product_name: "Schoggi Schokolade", supplier_id: 11, category_id: 3, quantity_per_unit: "100 - 100 g pieces", unit_price: Decimal.new("43.9000"), units_in_stock: 49, units_on_order: 0, reorder_level: 30, discontinued: false},
      %{id: 28, product_name: "Rössle Sauerkraut", supplier_id: 12, category_id: 7, quantity_per_unit: "25 - 825 g cans", unit_price: Decimal.new("45.6000"), units_in_stock: 26, units_on_order: 0, reorder_level: 0, discontinued: true},
      %{id: 29, product_name: "Thüringer Rostbratwurst", supplier_id: 12, category_id: 6, quantity_per_unit: "50 bags x 30 sausgs.", unit_price: Decimal.new("123.7900"), units_in_stock: 0, units_on_order: 0, reorder_level: 0, discontinued: true},
      %{id: 30, product_name: "Nord-Ost Matjeshering", supplier_id: 13, category_id: 8, quantity_per_unit: "10 - 200 g glasses", unit_price: Decimal.new("25.8900"), units_in_stock: 10, units_on_order: 0, reorder_level: 15, discontinued: false},
      %{id: 31, product_name: "Gorgonzola Telino", supplier_id: 14, category_id: 4, quantity_per_unit: "12 - 100 g pkgs", unit_price: Decimal.new("12.5000"), units_in_stock: 0, units_on_order: 70, reorder_level: 20, discontinued: false},
      %{id: 32, product_name: "Mascarpone Fabioli", supplier_id: 14, category_id: 4, quantity_per_unit: "24 - 200 g pkgs.", unit_price: Decimal.new("32.0000"), units_in_stock: 9, units_on_order: 40, reorder_level: 25, discontinued: false},
      %{id: 33, product_name: "Geitost", supplier_id: 15, category_id: 4, quantity_per_unit: "500 g", unit_price: Decimal.new("2.5000"), units_in_stock: 112, units_on_order: 0, reorder_level: 20, discontinued: false},
      %{id: 34, product_name: "Sasquatch Ale", supplier_id: 16, category_id: 1, quantity_per_unit: "24 - 12 oz bottles", unit_price: Decimal.new("14.0000"), units_in_stock: 111, units_on_order: 0, reorder_level: 15, discontinued: false},
      %{id: 35, product_name: "Steeleye Stout", supplier_id: 16, category_id: 1, quantity_per_unit: "24 - 12 oz bottles", unit_price: Decimal.new("18.0000"), units_in_stock: 20, units_on_order: 0, reorder_level: 15, discontinued: false},
      %{id: 36, product_name: "Inlagd Sill", supplier_id: 17, category_id: 8, quantity_per_unit: "24 - 250 g  jars", unit_price: Decimal.new("19.0000"), units_in_stock: 112, units_on_order: 0, reorder_level: 20, discontinued: false},
      %{id: 37, product_name: "Gravad lax", supplier_id: 17, category_id: 8, quantity_per_unit: "12 - 500 g pkgs.", unit_price: Decimal.new("26.0000"), units_in_stock: 11, units_on_order: 50, reorder_level: 25, discontinued: false},
      %{id: 38, product_name: "Côte de Blaye", supplier_id: 18, category_id: 1, quantity_per_unit: "12 - 75 cl bottles", unit_price: Decimal.new("263.5000"), units_in_stock: 17, units_on_order: 0, reorder_level: 15, discontinued: false},
      %{id: 39, product_name: "Chartreuse verte", supplier_id: 18, category_id: 1, quantity_per_unit: "750 cc per bottle", unit_price: Decimal.new("18.0000"), units_in_stock: 69, units_on_order: 0, reorder_level: 5, discontinued: false},
      %{id: 40, product_name: "Boston Crab Meat", supplier_id: 19, category_id: 8, quantity_per_unit: "24 - 4 oz tins", unit_price: Decimal.new("18.4000"), units_in_stock: 123, units_on_order: 0, reorder_level: 30, discontinued: false},
      %{id: 41, product_name: "Jack's New England Clam Chowder", supplier_id: 19, category_id: 8, quantity_per_unit: "12 - 12 oz cans", unit_price: Decimal.new("9.6500"), units_in_stock: 85, units_on_order: 0, reorder_level: 10, discontinued: false},
      %{id: 42, product_name: "Singaporean Hokkien Fried Mee", supplier_id: 20, category_id: 5, quantity_per_unit: "32 - 1 kg pkgs.", unit_price: Decimal.new("14.0000"), units_in_stock: 26, units_on_order: 0, reorder_level: 0, discontinued: true},
      %{id: 43, product_name: "Ipoh Coffee", supplier_id: 20, category_id: 1, quantity_per_unit: "16 - 500 g tins", unit_price: Decimal.new("46.0000"), units_in_stock: 17, units_on_order: 10, reorder_level: 25, discontinued: false},
      %{id: 44, product_name: "Gula Malacca", supplier_id: 20, category_id: 2, quantity_per_unit: "20 - 2 kg bags", unit_price: Decimal.new("19.4500"), units_in_stock: 27, units_on_order: 0, reorder_level: 15, discontinued: false},
      %{id: 45, product_name: "Rogede sild", supplier_id: 21, category_id: 8, quantity_per_unit: "1k pkg.", unit_price: Decimal.new("9.5000"), units_in_stock: 5, units_on_order: 70, reorder_level: 15, discontinued: false},
      %{id: 46, product_name: "Spegesild", supplier_id: 21, category_id: 8, quantity_per_unit: "4 - 450 g glasses", unit_price: Decimal.new("12.0000"), units_in_stock: 95, units_on_order: 0, reorder_level: 0, discontinued: false},
      %{id: 47, product_name: "Zaanse koeken", supplier_id: 22, category_id: 3, quantity_per_unit: "10 - 4 oz boxes", unit_price: Decimal.new("9.5000"), units_in_stock: 36, units_on_order: 0, reorder_level: 0, discontinued: false},
      %{id: 48, product_name: "Chocolade", supplier_id: 22, category_id: 3, quantity_per_unit: "10 pkgs.", unit_price: Decimal.new("12.7500"), units_in_stock: 15, units_on_order: 70, reorder_level: 25, discontinued: false},
      %{id: 49, product_name: "Maxilaku", supplier_id: 23, category_id: 3, quantity_per_unit: "24 - 50 g pkgs.", unit_price: Decimal.new("20.0000"), units_in_stock: 10, units_on_order: 60, reorder_level: 15, discontinued: false},
      %{id: 50, product_name: "Valkoinen suklaa", supplier_id: 23, category_id: 3, quantity_per_unit: "12 - 100 g bars", unit_price: Decimal.new("16.2500"), units_in_stock: 65, units_on_order: 0, reorder_level: 30, discontinued: false},
      %{id: 51, product_name: "Manjimup Dried Apples", supplier_id: 24, category_id: 7, quantity_per_unit: "50 - 300 g pkgs.", unit_price: Decimal.new("53.0000"), units_in_stock: 20, units_on_order: 0, reorder_level: 10, discontinued: false},
      %{id: 52, product_name: "Filo Mix", supplier_id: 24, category_id: 5, quantity_per_unit: "16 - 2 kg boxes", unit_price: Decimal.new("7.0000"), units_in_stock: 38, units_on_order: 0, reorder_level: 25, discontinued: false},
      %{id: 53, product_name: "Perth Pasties", supplier_id: 24, category_id: 6, quantity_per_unit: "48 pieces", unit_price: Decimal.new("32.8000"), units_in_stock: 0, units_on_order: 0, reorder_level: 0, discontinued: true},
      %{id: 54, product_name: "Tourtière", supplier_id: 25, category_id: 6, quantity_per_unit: "16 pies", unit_price: Decimal.new("7.4500"), units_in_stock: 21, units_on_order: 0, reorder_level: 10, discontinued: false},
      %{id: 55, product_name: "Pâté chinois", supplier_id: 25, category_id: 6, quantity_per_unit: "24 boxes x 2 pies", unit_price: Decimal.new("24.0000"), units_in_stock: 115, units_on_order: 0, reorder_level: 20, discontinued: false},
      %{id: 56, product_name: "Gnocchi di nonna Alice", supplier_id: 26, category_id: 5, quantity_per_unit: "24 - 250 g pkgs.", unit_price: Decimal.new("38.0000"), units_in_stock: 21, units_on_order: 10, reorder_level: 30, discontinued: false},
      %{id: 57, product_name: "Ravioli Angelo", supplier_id: 26, category_id: 5, quantity_per_unit: "24 - 250 g pkgs.", unit_price: Decimal.new("19.5000"), units_in_stock: 36, units_on_order: 0, reorder_level: 20, discontinued: false},
      %{id: 58, product_name: "Escargots de Bourgogne", supplier_id: 27, category_id: 8, quantity_per_unit: "24 pieces", unit_price: Decimal.new("13.2500"), units_in_stock: 62, units_on_order: 0, reorder_level: 20, discontinued: false},
      %{id: 59, product_name: "Raclette Courdavault", supplier_id: 28, category_id: 4, quantity_per_unit: "5 kg pkg.", unit_price: Decimal.new("55.0000"), units_in_stock: 79, units_on_order: 0, reorder_level: 0, discontinued: false},
      %{id: 60, product_name: "Camembert Pierrot", supplier_id: 28, category_id: 4, quantity_per_unit: "15 - 300 g rounds", unit_price: Decimal.new("34.0000"), units_in_stock: 19, units_on_order: 0, reorder_level: 0, discontinued: false},
      %{id: 61, product_name: "Sirop d'érable", supplier_id: 29, category_id: 2, quantity_per_unit: "24 - 500 ml bottles", unit_price: Decimal.new("28.5000"), units_in_stock: 113, units_on_order: 0, reorder_level: 25, discontinued: false},
      %{id: 62, product_name: "Tarte au sucre", supplier_id: 29, category_id: 3, quantity_per_unit: "48 pies", unit_price: Decimal.new("49.3000"), units_in_stock: 17, units_on_order: 0, reorder_level: 0, discontinued: false},
      %{id: 63, product_name: "Vegie-spread", supplier_id: 7, category_id: 2, quantity_per_unit: "15 - 625 g jars", unit_price: Decimal.new("43.9000"), units_in_stock: 24, units_on_order: 0, reorder_level: 5, discontinued: false},
      %{id: 64, product_name: "Wimmers gute Semmelknödel", supplier_id: 12, category_id: 5, quantity_per_unit: "20 bags x 4 pieces", unit_price: Decimal.new("33.2500"), units_in_stock: 22, units_on_order: 80, reorder_level: 30, discontinued: false},
      %{id: 65, product_name: "Louisiana Fiery Hot Pepper Sauce", supplier_id: 2, category_id: 2, quantity_per_unit: "32 - 8 oz bottles", unit_price: Decimal.new("21.0500"), units_in_stock: 76, units_on_order: 0, reorder_level: 0, discontinued: false},
      %{id: 66, product_name: "Louisiana Hot Spiced Okra", supplier_id: 2, category_id: 2, quantity_per_unit: "24 - 8 oz jars", unit_price: Decimal.new("17.0000"), units_in_stock: 4, units_on_order: 100, reorder_level: 20, discontinued: false},
      %{id: 67, product_name: "Laughing Lumberjack Lager", supplier_id: 16, category_id: 1, quantity_per_unit: "24 - 12 oz bottles", unit_price: Decimal.new("14.0000"), units_in_stock: 52, units_on_order: 0, reorder_level: 10, discontinued: false},
      %{id: 68, product_name: "Scottish Longbreads", supplier_id: 8, category_id: 3, quantity_per_unit: "10 boxes x 8 pieces", unit_price: Decimal.new("12.5000"), units_in_stock: 6, units_on_order: 10, reorder_level: 15, discontinued: false},
      %{id: 69, product_name: "Gudbrandsdalsost", supplier_id: 15, category_id: 4, quantity_per_unit: "10 kg pkg.", unit_price: Decimal.new("36.0000"), units_in_stock: 26, units_on_order: 0, reorder_level: 15, discontinued: false},
      %{id: 70, product_name: "Outback Lager", supplier_id: 7, category_id: 1, quantity_per_unit: "24 - 355 ml bottles", unit_price: Decimal.new("15.0000"), units_in_stock: 15, units_on_order: 10, reorder_level: 30, discontinued: false},
      %{id: 71, product_name: "Flotemysost", supplier_id: 15, category_id: 4, quantity_per_unit: "10 - 500 g pkgs.", unit_price: Decimal.new("21.5000"), units_in_stock: 26, units_on_order: 0, reorder_level: 0, discontinued: false},
      %{id: 72, product_name: "Mozzarella di Giovanni", supplier_id: 14, category_id: 4, quantity_per_unit: "24 - 200 g pkgs.", unit_price: Decimal.new("34.8000"), units_in_stock: 14, units_on_order: 0, reorder_level: 0, discontinued: false},
      %{id: 73, product_name: "Röd Kaviar", supplier_id: 17, category_id: 8, quantity_per_unit: "24 - 150 g jars", unit_price: Decimal.new("15.0000"), units_in_stock: 101, units_on_order: 0, reorder_level: 5, discontinued: false},
      %{id: 74, product_name: "Longlife Tofu", supplier_id: 4, category_id: 7, quantity_per_unit: "5 kg pkg.", unit_price: Decimal.new("10.0000"), units_in_stock: 4, units_on_order: 20, reorder_level: 5, discontinued: false},
      %{id: 75, product_name: "Rhönbräu Klosterbier", supplier_id: 12, category_id: 1, quantity_per_unit: "24 - 0.5 l bottles", unit_price: Decimal.new("7.7500"), units_in_stock: 125, units_on_order: 0, reorder_level: 25, discontinued: false},
      %{id: 76, product_name: "Lakkalikööri", supplier_id: 23, category_id: 1, quantity_per_unit: "500 ml", unit_price: Decimal.new("18.0000"), units_in_stock: 57, units_on_order: 0, reorder_level: 20, discontinued: false},
      %{id: 77, product_name: "Original Frankfurter grüne Soße", supplier_id: 12, category_id: 2, quantity_per_unit: "12 boxes", unit_price: Decimal.new("13.0000"), units_in_stock: 32, units_on_order: 0, reorder_level: 15, discontinued: false}
    ]
  end

  def shippers_data do
    [
      %{id: 1, company_name: "Speedy Express", phone: "(503) 555-9831"},
      %{id: 2, company_name: "United Package", phone: "(503) 555-3199"},
      %{id: 3, company_name: "Federal Shipping", phone: "(503) 555-9931"}
    ]
  end

  def regions_data do
    [
      %{id: 1, region_description: "Eastern"},
      %{id: 2, region_description: "Western"},
      %{id: 3, region_description: "Northern"},
      %{id: 4, region_description: "Southern"}
    ]
  end

  def territories_data do
    [
      %{territory_id: "01581", territory_description: "Westboro", region_id: 1},
      %{territory_id: "01730", territory_description: "Bedford", region_id: 1},
      %{territory_id: "01833", territory_description: "Georgetow", region_id: 1},
      %{territory_id: "02116", territory_description: "Boston", region_id: 1},
      %{territory_id: "02139", territory_description: "Cambridge", region_id: 1},
      %{territory_id: "02184", territory_description: "Braintree", region_id: 1},
      %{territory_id: "02903", territory_description: "Providence", region_id: 1},
      %{territory_id: "03049", territory_description: "Hollis", region_id: 3},
      %{territory_id: "03801", territory_description: "Portsmouth", region_id: 3},
      %{territory_id: "06897", territory_description: "Wilton", region_id: 1},
      %{territory_id: "07960", territory_description: "Morristown", region_id: 1},
      %{territory_id: "08837", territory_description: "Edison", region_id: 1},
      %{territory_id: "10019", territory_description: "New York", region_id: 1},
      %{territory_id: "10038", territory_description: "New York", region_id: 1},
      %{territory_id: "11747", territory_description: "Mellvile", region_id: 1},
      %{territory_id: "14450", territory_description: "Fairport", region_id: 1},
      %{territory_id: "19428", territory_description: "Philadelphia", region_id: 3},
      %{territory_id: "19713", territory_description: "Neward", region_id: 1},
      %{territory_id: "20852", territory_description: "Rockville", region_id: 1},
      %{territory_id: "27403", territory_description: "Greensboro", region_id: 1},
      %{territory_id: "27511", territory_description: "Cary", region_id: 1},
      %{territory_id: "29202", territory_description: "Columbia", region_id: 4},
      %{territory_id: "30346", territory_description: "Atlanta", region_id: 4},
      %{territory_id: "31406", territory_description: "Savannah", region_id: 4},
      %{territory_id: "32859", territory_description: "Orlando", region_id: 4},
      %{territory_id: "33607", territory_description: "Tampa", region_id: 4},
      %{territory_id: "40222", territory_description: "Louisville", region_id: 1},
      %{territory_id: "44122", territory_description: "Beachwood", region_id: 3},
      %{territory_id: "45839", territory_description: "Findlay", region_id: 3},
      %{territory_id: "48075", territory_description: "Southfield", region_id: 3},
      %{territory_id: "48084", territory_description: "Troy", region_id: 3},
      %{territory_id: "48304", territory_description: "Bloomfield Hills", region_id: 3},
      %{territory_id: "53404", territory_description: "Racine", region_id: 3},
      %{territory_id: "55113", territory_description: "Roseville", region_id: 3},
      %{territory_id: "55439", territory_description: "Minneapolis", region_id: 3},
      %{territory_id: "60179", territory_description: "Hoffman Estates", region_id: 2},
      %{territory_id: "60601", territory_description: "Chicago", region_id: 2},
      %{territory_id: "72716", territory_description: "Bentonville", region_id: 4},
      %{territory_id: "75234", territory_description: "Dallas", region_id: 4},
      %{territory_id: "78759", territory_description: "Austin", region_id: 4},
      %{territory_id: "80202", territory_description: "Denver", region_id: 2},
      %{territory_id: "80909", territory_description: "Colorado Springs", region_id: 2},
      %{territory_id: "85014", territory_description: "Phoenix", region_id: 2},
      %{territory_id: "85251", territory_description: "Scottsdale", region_id: 2},
      %{territory_id: "90405", territory_description: "Santa Monica", region_id: 2},
      %{territory_id: "94025", territory_description: "Menlo Park", region_id: 2},
      %{territory_id: "94105", territory_description: "San Francisco", region_id: 2},
      %{territory_id: "95008", territory_description: "Campbell", region_id: 2},
      %{territory_id: "95054", territory_description: "Santa Clara", region_id: 2},
      %{territory_id: "95060", territory_description: "Santa Cruz", region_id: 2},
      %{territory_id: "98004", territory_description: "Bellevue", region_id: 2},
      %{territory_id: "98052", territory_description: "Redmond", region_id: 2},
      %{territory_id: "98104", territory_description: "Seattle", region_id: 2}
    ]
  end

  def employee_territories_data do
    [
      %{employee_id: 1, territory_id: "06897"},
      %{employee_id: 1, territory_id: "19713"},
      %{employee_id: 2, territory_id: "01581"},
      %{employee_id: 2, territory_id: "01730"},
      %{employee_id: 2, territory_id: "01833"},
      %{employee_id: 2, territory_id: "02116"},
      %{employee_id: 2, territory_id: "02139"},
      %{employee_id: 2, territory_id: "02184"},
      %{employee_id: 2, territory_id: "40222"},
      %{employee_id: 3, territory_id: "30346"},
      %{employee_id: 3, territory_id: "31406"},
      %{employee_id: 3, territory_id: "32859"},
      %{employee_id: 3, territory_id: "33607"},
      %{employee_id: 4, territory_id: "20852"},
      %{employee_id: 4, territory_id: "27403"},
      %{employee_id: 4, territory_id: "27511"},
      %{employee_id: 5, territory_id: "02903"},
      %{employee_id: 5, territory_id: "07960"},
      %{employee_id: 5, territory_id: "08837"},
      %{employee_id: 5, territory_id: "10019"},
      %{employee_id: 5, territory_id: "10038"},
      %{employee_id: 5, territory_id: "11747"},
      %{employee_id: 5, territory_id: "14450"},
      %{employee_id: 6, territory_id: "85014"},
      %{employee_id: 6, territory_id: "85251"},
      %{employee_id: 6, territory_id: "98004"},
      %{employee_id: 6, territory_id: "98052"},
      %{employee_id: 6, territory_id: "98104"},
      %{employee_id: 7, territory_id: "60179"},
      %{employee_id: 7, territory_id: "60601"},
      %{employee_id: 7, territory_id: "80202"},
      %{employee_id: 7, territory_id: "80909"},
      %{employee_id: 7, territory_id: "90405"},
      %{employee_id: 7, territory_id: "94025"},
      %{employee_id: 7, territory_id: "94105"},
      %{employee_id: 7, territory_id: "95008"},
      %{employee_id: 7, territory_id: "95054"},
      %{employee_id: 7, territory_id: "95060"},
      %{employee_id: 8, territory_id: "19428"},
      %{employee_id: 8, territory_id: "44122"},
      %{employee_id: 8, territory_id: "45839"},
      %{employee_id: 8, territory_id: "48075"},
      %{employee_id: 8, territory_id: "48084"},
      %{employee_id: 8, territory_id: "48304"},
      %{employee_id: 8, territory_id: "53404"},
      %{employee_id: 8, territory_id: "55113"},
      %{employee_id: 8, territory_id: "55439"},
      %{employee_id: 9, territory_id: "03049"},
      %{employee_id: 9, territory_id: "03801"},
      %{employee_id: 9, territory_id: "29202"},
      %{employee_id: 9, territory_id: "72716"},
      %{employee_id: 9, territory_id: "75234"},
      %{employee_id: 9, territory_id: "78759"}
    ]
  end
end
