defmodule SelectoNorthwind.SavedViewContext do
  @moduledoc """
  Context module implementing SelectoComponents.SavedViews behavior.

  This module provides a `use` macro that adds saved views functionality
  to your domain modules.

  Generated by mix selecto.gen.saved_views

  ## Usage

      defmodule MyApp.Domains.UserDomain do
        use SelectoNorthwind.SavedViewContext
        
        # ... rest of domain configuration
      end
  """

  defmacro __using__(_opts \\ []) do
    quote do
      @behaviour SelectoComponents.SavedViews

      import Ecto.Query

      def get_view(name, context) do
        context = scoped_context(context)

        q =
          from v in SelectoNorthwind.SavedView,
            where: ^context == v.context,
            where: ^name == v.name

        SelectoNorthwind.Repo.one(q)
      end

      def save_view(name, context, params) do
        context = scoped_context(context)

        case get_view(name, context) do
          nil ->
            SelectoNorthwind.Repo.insert!(%SelectoNorthwind.SavedView{
              name: name,
              context: context,
              params: params
            })

          view ->
            update_view(view, params)
        end
      end

      defp update_view(view, params) do
        {:ok, view} =
          SelectoNorthwind.SavedView.changeset(view, %{params: params})
          |> SelectoNorthwind.Repo.update()

        view
      end

      def get_view_names(context) do
        context = scoped_context(context)

        q =
          from v in SelectoNorthwind.SavedView,
            select: v.name,
            where: ^context == v.context,
            order_by: v.name

        SelectoNorthwind.Repo.all(q)
      end

      def list_views(context) do
        context = scoped_context(context)

        q =
          from v in SelectoNorthwind.SavedView,
            where: ^context == v.context,
            order_by: [desc: v.updated_at, asc: v.name]

        SelectoNorthwind.Repo.all(q)
      end

      def delete_view(name, context) do
        context = scoped_context(context)

        case get_view(name, context) do
          nil ->
            {:error, :not_found}

          view ->
            SelectoNorthwind.Repo.delete(view)
        end
      end

      def rename_view(old_name, new_name, context) do
        context = scoped_context(context)
        trimmed_name = String.trim(new_name || "")

        cond do
          trimmed_name == "" ->
            {:error, :invalid_name}

          old_name == trimmed_name ->
            case get_view(old_name, context) do
              nil -> {:error, :not_found}
              view -> {:ok, view}
            end

          true ->
            case get_view(old_name, context) do
              nil ->
                {:error, :not_found}

              view ->
                if get_view(trimmed_name, context) do
                  {:error, :already_exists}
                else
                  view
                  |> SelectoNorthwind.SavedView.changeset(%{name: trimmed_name})
                  |> SelectoNorthwind.Repo.update()
                end
            end
        end
      end

      def decode_view(view) do
        # Return params to use for view restoration
        view.params
      end

      defp scoped_context(context) do
        case context do
          %{} = context_map ->
            raw_context =
              Map.get(context_map, :context) ||
                Map.get(context_map, "context") ||
                Map.get(context_map, :path) ||
                Map.get(context_map, "path") ||
                "default"

            tenant_context =
              Map.get(context_map, :tenant) ||
                Map.get(context_map, "tenant") ||
                %{
                  tenant_id: Map.get(context_map, :tenant_id) || Map.get(context_map, "tenant_id")
                }

            if Code.ensure_loaded?(SelectoComponents.Tenant) do
              SelectoComponents.Tenant.scoped_context(raw_context, tenant_context)
            else
              raw_context
            end

          _ ->
            context
        end
      end
    end
  end
end
