version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/selecto_northwind:cached
    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db
    environment:
      DATABASE_URL: ecto://postgres:postgres@localhost/selecto_northwind_dev
      MIX_ENV: dev

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: selecto_northwind_dev

volumes:
  postgres-data:
